/* Generated By:JavaCC: Do not edit this line. AnalyseurSyntaxiqueConstants.java */
// Import tous les package necessaires 

package fr.insarouen.iti.prog.compilation.interpreteur.analyseurs;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalyseurSyntaxiqueConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PARAG = 6;
  /** RegularExpression Id. */
  int PARAD = 7;
  /** RegularExpression Id. */
  int AFF = 8;
  /** RegularExpression Id. */
  int VIRGULE = 9;
  /** RegularExpression Id. */
  int IDF = 10;
  /** RegularExpression Id. */
  int CONST = 11;
  /** RegularExpression Id. */
  int CHIFFRE = 12;
  /** RegularExpression Id. */
  int NB_ENTIER = 13;
  /** RegularExpression Id. */
  int LETTRE = 14;
  /** RegularExpression Id. */
  int CHAINE = 15;
  /** RegularExpression Id. */
  int ID = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\",\"",
    "<IDF>",
    "<CONST>",
    "<CHIFFRE>",
    "<NB_ENTIER>",
    "<LETTRE>",
    "<CHAINE>",
    "<ID>",
  };

}
